### ISSUE TITLE
Quick Start wiki page update: Additional argument to RCTRootView's initializer

### ISSUE THREAD

**Issue by tomazzlender** [omcljs/ambly#100]
It seems that wiki page [Quick Start](https://github.com/omcljs/ambly/wiki/ClojureScript-React-Native-Quick-Start) should be updated because of [breaking changes in React Native v0.11.0-rc](https://github.com/facebook/react-native/releases/tag/v0.11.0-rc) regarding additional argument to RCTRootView's initializer.

In file `AppDelegate.m` there should be

``` objective-c
// Set up a root view using the bridge defined above
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"AwesomeProject"
                                             initialProperties:nil];
```

instead of

``` objective-c
// Set up a root view using the bridge defined above
RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"AwesomeProject"];
```

This resolves the error `No visible @interface for 'RCTRootView' declares the selector...`.

**Comment by coyotespike** [comment]
Thanks @tomazzlender, this fixed this issue for me as well. Xcode cannot build with this error.

**Comment by mfikes** [comment]
Fixed in Wiki
