### ISSUE TITLE
"umount" exception

### ISSUE THREAD

**Issue by coyotespike** [omcljs/ambly#101]
I was following along with the demo project. After I run `script/repl` and choose 1, I get `java.io.IOException: Cannot run program "umount": error=2, No such file or directory`.

I'm on OSX - is this a linux command, or am I missing a key package? The app itself runs in the simulator, but with this error the REPL won't connect.

**Comment by mfikes** [comment]
@coyotespike Please try running `umount` directly from within the terminal. If it works, `umount` by itself will simply print usage information. It is installed in `/sbin/umount` so my hunch is your shell doesn't have `/sbin` in its path.

**Comment by coyotespike** [comment]
Yes, I get `umount: command not found`, so probably you're right. I'll check into my path.

**Comment by coyotespike** [comment]
Thanks Mike - I added `export PATH=/sbin:$PATH` to my .bashrc, and it fixed it! Next in my sights, `mount_webdav` ;-)
