### ISSUE TITLE
Unable to mount WebDAV

### ISSUE THREAD

**Issue by coyotespike** [omcljs/ambly#103]
Whether I attempt to connect to my running app from `natal` or via the Quick Start method, I'm getting this error.

```
java.io.IOException: Unable to mount WebDAV at http://127.0.0.1:49155
    at ambly.core$eval4749$fn__4750.invoke(core.clj:437)
    at clojure.lang.MultiFn.invoke(MultiFn.java:243)
    at ambly.core$setup.invoke(core.clj:521)
    at ambly.core.JscEnv._setup(core.clj:634)
```

I then followed the steps outlined in Connectivity. By using `sudo mount_webdav http://127.0.0.1:49155 /Volumes/TestAmbly`, I can confirm that this works with `sudo ls`. Neither command works without `sudo`.

Do I need to modify my permissions for mount_webdav in order to allow Ambly to work its magic? Thanks for any help.

**Comment by mfikes** [comment]
@coyotespike What kind of OS X account do you have? (I generally do dev with an Admin account; perhaps things break with non-Admin accounts.)

**Comment by coyotespike** [comment]
It's an Admin account...huh. The Apple man page on mount_webdav didn't help me, sadly.

**Comment by mfikes** [comment]
@coyotespike Perhaps you have a stale and misbehaving mount point. I'd suggest using `sudo` to blow it away and perhaps also rebooting if needed.

**Comment by coyotespike** [comment]
Thanks, I'll try both of those!

**Comment by coyotespike** [comment]
Rebooting didn't help, but `ls /Volumes` showed two Ambly mount points, which doubtless got there when I was messing around earlier. `rm -rf` cleared these, and now it's working! Thanks very much for your help!
And thanks for making Ambly, as well. This is my first foray into apps and it's exciting to see how much of my ClojureScript knowledge I can apply here.

**Comment by mfikes** [comment]
@coyotespike Cool. I've had problems with mount points gone awry in the past as well, having to roll my sleeves up and blow away stale mount points. I've updated the Connectivity wiki with advice that mimics the above.
