### ISSUE TITLE
Potential Leak?

### ISSUE THREAD

**Issue by zwang** [omcljs/ambly#107]
I am using Xcode 7.1.1 with Swift 2.1 on Mac OS X 10.11.1. It shows an an warning about potential object leak shown as below:

<img width="1304" alt="screen shot 2015-11-24 at 1 17 05 pm" src="https://cloud.githubusercontent.com/assets/1171212/11381015/6b7ac7c0-92ae-11e5-81e6-e6c861b5a126.png">

**Comment by zwang** [comment]
More potential leaks in Release Mode.

![screen shot 2015-11-24 at 5 57 09 pm](https://cloud.githubusercontent.com/assets/1171212/11386587/7dfb46b2-92d7-11e5-8952-f0a6a5418cd0.png)

**Comment by mfikes** [comment]
https://github.com/omcljs/ambly/commit/e8f69492f187da970b686963266f828c4dd6908b
