### ISSUE TITLE
How to stop the WebDav server sonner after JSContext is no longer valid

### ISSUE THREAD

**Issue by zwang** [omcljs/ambly#108]
My use case is that after I am done with one JSContext, I will exit a view and de-reference the JSContext, ABYServer by setting them `nil`. I found that the WebDav server still can be connected but when I connect, it will trigger a `EXC_BAD_ACCESS` error shown below:
![screen shot 2015-11-24 at 5 52 44 pm](https://cloud.githubusercontent.com/assets/1171212/11386201/37b0e5b6-92d4-11e5-8030-4dc2fa126edb.png)

Can I stop the WebDav server as soon as the socket connection is not usable?

**Comment by mfikes** [comment]
@zwang I suppose Ambly currently has no shutdown lifecycle methods, but it could use them. Happy to take a PR (Ambly is under a CA). Otherwise maybe I can add some lifecycle methods.

**Comment by zwang** [comment]
@mfikes I see. I will take a look this week then. Will sign the CA later. Thank you. :)

**Comment by mfikes** [comment]
https://github.com/omcljs/ambly/commit/e8f69492f187da970b686963266f828c4dd6908b
