### ISSUE TITLE
If you try to use tvOS, linking fails

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#116]
You get

```
ld: library not found for -lAmbly
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This can be worked around by revising the `ObjectiveC/Ambly Demo/Podfile` to simply specify

```
platform :tvos, '9.0'
```

instead of using the `target` conditional blocks and then running `pod install`.

Interestingly, after doing this some state is kept around and the problem doesn't recur afterwards.

**Comment by mfikes** [comment]
Perhaps fixed with https://github.com/omcljs/ambly/commit/698022edbf4f9d38b9b597b57f4a37ef04859260

**Comment by sherbondy** [comment]
Yeah, think so. Just did a fresh clone and build on the tvos branch of both targets. Would be great for someone else to have a go with their Xcode setup just to verify that everything's replicable.

**Comment by mfikes** [comment]
Confirmed fixed. Tried with a fresh clone on several boxes.
