### ISSUE TITLE
Disable device sleeping

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#20]
I _think_ that when you have Xcode connected to your device, the device doesn't sleep.

If disconnect the USB cable, you can actually still develop (at least the ClojureScript aspect), because of the use of TCP-connected REPL and WebDAV. And in this situation clearly the device can go to sleep within a minute or so.

So this ticket is to consider disabling sleep if developing in this mode.

Here is a reference
http://stackoverflow.com/questions/12661004/how-to-disable-enable-the-sleep-mode-programmatically-in-ios

**Comment by swannodette** [comment]
This seems like something we could provide as a default for debug builds so it's automatically disabled for production?

**Comment by mfikes** [comment]
Yes. Was thinking the same. :)
