### ISSUE TITLE
Race appears to exist between writing WebDAV files and them being read

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#25]
A large sleep is currently in the code to avoid it. The odd thing is that I don't recall seeing this earlier.

**Comment by swannodette** [comment]
yeah I was somewhat worried about this. We might `goog.require` to queue until WebDAV server acknowledges the write? An arbitrary sleep time seems pretty brittle.

**Comment by mfikes** [comment]
@swannodette Looks like there was no "race". I had really botched the writing of ambly_repl_deps.js (analog of node_repl.deps) by failing to redirect its output to the WebDAV target. Fixing this cleared all of this up! :)

**Comment by swannodette** [comment]
@mfikes awesome! :)
