### ISSUE TITLE
`require` `:reload` failing in Cursive

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#28]
1. Add `[com.cemerick/piggieback "0.1.5"]` to your project dependencies.
2. Mix in the Piggyback middleware by adding `:repl-options {:nrepl-middleware [cemerick.piggieback/wrap-cljs-repl]}` to your `project.clj`.
3. Issue the following two forms in the Cursive REPL

``` clojure
(require
  '[cljs.repl :as repl]
  '[cemerick.piggieback]
  '[ambly.repl.jsc :as jsc])
```

``` clojure
(cemerick.piggieback/cljs-repl
  :repl-env (jsc/repl-env)
  :optimizations :none
  :cache-analysis true
  :source-map true)
```

Then edit a file in `foo.bar` namespace and issue `(require 'foo.bar :reload)`. You won't see new `def`s.

Perhaps something with the auto-configuration of `:output-dir` with nREPL needs to be looked at.

**Comment by mfikes** [comment]
I don't see the WebDAV logging in Xcode for this use case that you would normally see.

**Comment by mfikes** [comment]
My hunch is that Piggieback's [`cljs-repl`](https://github.com/cemerick/piggieback/blob/0.1.5/src/cemerick/piggieback.clj#L159), which calls Ambly's `-setup`, probably doesn't pass back out `:merge-opts` to the compiler environment as in this ClojureScript [update](https://github.com/clojure/clojurescript/commit/62e4b349f966e6895dae5e0073b5df894a492c0d).

**Comment by swannodette** [comment]
It's a new contract for sure, I'm pretty in the dark about how piggieback works should probably ping @cemerick about this.

**Comment by mfikes** [comment]
@swannodette Yes. I'm experimenting piggieback to see if I can get it to honor the new contract (if it is not already). If I find out more, we can see if @cemerick would incorporate it (or take a PR).

**Comment by mfikes** [comment]
The deployed Piggieback 0.1.6-SNAPSHOT now has support for `:merge-opts`.
