### ISSUE TITLE
REPL runs fine without locally-built master ClojureScript

### ISSUE THREAD

**Issue by daveliepmann** [omcljs/ambly#30]
From the README: 

> NOTE: ClojureScript master is currently required. (You will need to get the latest, build it, and update the project.clj file in ambly/Clojure to refer to your locally-built copy.)

My REPL seems to run fine out of the box without any locally-built CLJS master build that I know of.

**Comment by swannodette** [comment]
@daveliepmann Ambly is relying on features still under active development in the ClojureScript compiler. So while it might work without installing master, there's no guarantee at least in the very near future.

**Comment by mfikes** [comment]
@daveliepmann Cool. Yes, the only bit really needed from master is the ability to communicate `:output-dir` to the compiler environment. So, if you try to evaluate forms, that may work, but if you try to `(require ..)` some code from your namespace, that may not work.

**Comment by daveliepmann** [comment]
Got it, thanks guys.
