### ISSUE TITLE
Evaluating long expression misbehaves

### ISSUE THREAD

**Issue by mfikes** [omcljs/ambly#74]
If you paste the following in to the Ambly REPL

``` clojure
(some-> 1 inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc inc)
```

You will get back `254`. But if you add one more `inc`, then something messes up and the form is not evaluated and the terminal becomes unusable.

**Comment by mfikes** [comment]
Same things happens with Quick Start browser REPL. If I can isolate what this is, I'll submit a useful bug report against ClojureScript.

**Comment by swannodette** [comment]
@mfikes isn't this the JavaScriptCore nested invoke bug? Can't really do much about this in REPLs as advanced optimizations don't kick in.

**Comment by mfikes** [comment]
@swannodette Good thought, but no: I just retried and am also able to reproduce it with Quick Start browser REPL against Firefox.

**Comment by mfikes** [comment]
@swannodette Interestingly, it is related to the OS X terminal. You can essentially reproduce is with something as simple as

```
cat > foo.txt
```

Then paste in the long line and try to edit it to add the last `inc`. You can't.

Interestingly `lein repl` overcomes the issue (will look to see if it messes with terminal I/O line length limitations).

**Comment by mfikes** [comment]
It appears that the terminal has a limit of 1024 characters. (See [this SO](http://superuser.com/questions/264407/macosx-10-6-7-cuts-off-stdin-at-1024-chars).)

Interestingly, `lein repl` probably avoids this by [trptcolin/reply](https://github.com/trptcolin/reply) employing [jline/jline2](https://github.com/jline/jline2).

Ideally, Ambly wouldn't pursue things like these on its own if it can instead be implemented in the base REPL support. Closing for now.
