### ISSUE TITLE
Different context? or perhaps race condition

### ISSUE THREAD

**Issue by invaliduser** [omcljs/ambly#91]
1. Follow the steps as outlined in [ClojureScript React Native Quick Start](https://github.com/omcljs/ambly/wiki/ClojureScript-React-Native-Quick-Start)
2. Upon selecting "[1] AwesomeProject on iPhoneSimulator" at the REPL, Xcode logs a bunch of warnings (EDIT: normal), and the REPL is blind to variables it should be able to see:
   
   To quit, type: :cljs/quit
   cljs.user=> ((fn render [] (.requestAnimationFrame js/window render)))
   ReferenceError: Can't find variable: window
   cljs$user$render (NO_SOURCE_FILE)
   global code (NO_SOURCE_FILE)

I will keep investigating this and will report back if I figure it out. (This may be related to the Ubuntu race condition, but I'm running on OS X, so we'll see).

EDIT: markdown problems, will edit later (fun fact: the clojure [parameter] (body) syntax matches markdown's [link title] (link address) syntax)

**Comment by mfikes** [comment]
The warnings in Xcode are fairly normal. This may help: https://github.com/omcljs/ambly/wiki/Connectivity

**Comment by invaliduser** [comment]
All connected!  Thanks.

**Comment by mfikes** [comment]
@invaliduser For #90, I've expanded the instructions that Ambly prints to detail how to eliminate the delayed upload to the WebDAV server https://github.com/omcljs/ambly/blob/master/Clojure/src/ambly/core.clj#L465

On OS X this issue doesn't occur. But you're revised description includes what appears to be `((fn render ))` which is probably a typo, where the root problem is an inability to see `js/window`?

I tried just now in a fresh directory and the `requestAnimationFrame` bit worked for me:

``` clojure
cljs.user=> ((fn render []
  (.requestAnimationFrame js/window render)))
1
```

**Comment by mfikes** [comment]
@invaliduser Do you see the initial screen displaying "Welcome to React Native!" in the UI, prior to running the REPL?

**Comment by invaliduser** [comment]
The default one put in by the facebook team?  Yes.

Something strange is going on here, though:
- _Sometimes_ the workaround "render" fn will evaluate as normal.  Sometimes it will fail from the environment failing to find `window`.
- even in the event that the workaround fn succeeds, `require` seems to fail at actually interning symbols:
  
  cljs.user=> (require 'awesome-project.core)
  nil
  
  cljs.user=> js/awesome_project
  #js {:core #js {}}

and the UI fails to respond to `require` statements (including clicking, as I was worried the workaround didn't work).
- to complicate things, sometimes it succeeds and I can explore the namespace for, say, `widget`.  In that case, however, the environment seems to fail to find `om`.  I discovered this when I tried manually typing the rendering code into the repl (I was not rigorous here, though; I may have neglected to do the ns -> bootstrap om -> ns setup through the repl, though my .core file is just copy-pasted.
- I have, actually, had the entire demo work once (literally one refresh cycle of the simulator, ha), which is what makes me wonder if it's a race condition or something equally demonic to debug.  
- I'm printing all the js strings that ABYServer gets from the REPL, and everything seems normal; next I'll look into the context, as it seems very strange for `js/window` to be giving errors.

**Comment by mfikes** [comment]
Interesting. One idea is to flush out any residual state: Stop the iOS app in the simulator, and do _iOS Simulator_ > _Reset Content and Settings_, and also look for any target and out directories that might be sitting in the same directory as your `project.clj` file, and look for any stale `/Volumes/Ambly-*` mount directories and remove them.

Then after this, fire up the app in Xcode, followed by connecting the REPL, to see if things work cleanly.

If not, perhaps you can share your code tree; I'd be interested in taking a look. You mentioned manually doing `awesome-app.core` at the REPL; perhaps there is a subtle issue when doing it that way.

Another thought that might be worth trying: There is a working app with startup instructions here https://github.com/mfikes/qttt#react-native-port that might be interesting for you to try to see if it fails in some interesting way that is specific to your environment (older Xcode or iOS simulators, etc.)

**Comment by invaliduser** [comment]
Narrative as I go:
- No stale /Volumes/Ambly mount points, being removed as intended
- reset content and settings, closed simulator, rebuilt app/connected with new repl session
- connected, everything worked,
- at this point remembered to check `out`/`target`, which may or may not be holdovers from previous; left them alone
- `swap!` updating and edit-then-namespace-reload both work

So, all seems to be working.  If I can reproduce I'll investigate more.

For reference: Xcode 6.3.1,
iOS simulator 8.3 (SimulatorApp-565.9 CoreSimulator-117.15)
  [[org.clojure/clojure "1.7.0-
RC1"]
   [org.clojure/clojurescript "0.0-3269"]
   [org.omcljs/om "0.8.8"]
   [org.omcljs/ambly "0.5.0"]]

**Comment by mfikes** [comment]
Cool!
