### ISSUE TITLE
Support for Boot

### ISSUE THREAD

**Issue by elibdev** [omcljs/ambly#94]
I've started using Ambly in a Boot development environment, and I've written a small Boot task to get Ambly up and running. I figure there are other people interested in doing the same thing, and having the Boot setup along with the Leiningen setup in the repo might help. 

If there's some other reason for using Leiningen instead of Boot that I haven't come across, I'd love to know. Otherwise if this sounds like something interesting, I'd love to clean it up a bit and submit a pull request. 

Thanks!
Eli

**Comment by mfikes** [comment]
That'd be cool. (I have no experience with Boot.) If you'd like to contribute, Omcljs projects are covered by a CA that you'd need to sign with David.

**Comment by elibdev** [comment]
Cool, I'll write him now.

**Comment by mfikes** [comment]
@edbedbe I haven't looked at the related PR yet. Today, Ambly doesn't require or even have `lein` support for end users. (It is just a JAR on Clojars, and related CocoaPods artifacts) I'm curious if Boot requires something additional, or if this is really just for people who have cloned the Ambly repo and would want to use Boot when messing with Ambly itself.

**Comment by elibdev** [comment]
It's just for people who have cloned the repo and want to mess around with Ambly using Boot. It's really small, and nonessential. Just a slight convenience, the Boot equivalent of the shell script included for use with Leiningen. I definitely get it if you think it may not be worth it to put it in. I had reservations about it myself, which is why I opened up the issue first. :)

**Comment by mfikes** [comment]
Cool. That's perfectly fine IMHO. Especially since it has no real impact to “end users” it makes it a no-brainier to do. Do you have a CA signed?

**Comment by elibdev** [comment]
Awesome. No, I wrote David and I'm waiting on a response.

**Comment by swannodette** [comment]
@mfikes @edbedbe has signed & returned the CA.

**Comment by mfikes** [comment]
Fixed
