### ISSUE TITLE
issue with ClojureScript React Native Quick Start

### ISSUE THREAD

**Issue by pbaille** [omcljs/ambly#98]
Hello,

I'm trying to follow the ClojureScript React Native Quick Start, the simulator launch the app correctly and few second after i've got this error:

{"type":"Internal Error","message":"react-packager has encountered an internal error, please check your terminal error output for more details"}

here's the project repo: https://github.com/pbaille/Awesome

**Comment by mfikes** [comment]
@pbaille I cloned your project and it works fine for me.

**Comment by pbaille** [comment]
I've fixed the issue with 'brew update watchman'
